name: netflix_ui
description: "A new Flutter project."
publish_to: 'none' # This prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  video_player: ^2.8.1
  chewie: ^1.7.5
  package_info_plus: ^8.3.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  iconsax: ^0.0.8
  lottie: ^2.7.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/intro_banner.png
    - assets/images/intro_banner2.jpg
    - assets/images/third_image.jpg
    - assets/images/Netflix_Logo.png
    - assets/images/Netflix_Symbol.png
    - assets/animations/netflix_swoop.json
    - assets/animations/intro2.json
    - assets/images/second_image.jpg



  fonts:
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf

flutter_native_splash:
  color: "#000000"
  android: true
  ios: true
  fullscreen: true
